# ----------- CONFIGURABLE START -----------
title:            "Zehui Chen"
description:      "~"
url:              https://lovesnowbest.site # Site url, without a slash at the end.
signoff:          "lovesnowbest" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Friends
    url:          /friends
  - name:         Github
    url:          https://github.com/zehuichen123/
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"